### ISSUE TITLE
Pittsburgh City Council Scraper Not Working And Pandemic Changes

### ISSUE THREAD

**Issue by maxachis** [pgh-public-meetings/city-scrapers-pitt#120]
The [Pittsburgh City Council web scraper](https://github.com/pgh-public-meetings/city-scrapers-pitt/blob/master/city_scrapers/spiders/pitt_city_council.py) is currently not working, and changes have been made to the format of meetings, as described below

Pittsburgh city council meeting remotely, currently via conference call, with some meeting in the closed-to-the-public council chambers.

Members of the public have been instructed to send public comment to cityclerksoffice@pittsburghpa.gov or by U.S. mail.

As always, City Council agendas and livestreamed meetings can be accessed at pittsburgh.legistar.com/calendar. Meetings continue to be cablecast on the City Channel, which can be found on Comcast channels 13 and 14 / Verizon channels 44 and 45.

**Comment by bonfirefan** [comment]
According to the City Website:
**IMPORTANT COUNCIL MEETING INFORMATION**
Due to the COVID-19 protective guidelines set forth by the federal, state, and local governments, we have altered our live meeting coverage
Effective April 7, 2020, City Council meetings will be prerecorded and replayed on City Channel Pittsburgh (https://pittsburghpa.gov/innovation-performance/city-channel). You may also access the meeting videos online (https://pittsburgh.legistar.com/Calendar.aspx)
Public comments will need to be submitted to the City Clerk’s Office by the close of business (cityclerksoffice@pittsburghpa.gov) Monday in order to be included in the official record for Council’s meetings.
https://pittsburghpa.gov/clerk/council-meetings

**Comment by maxachis** [comment]
These issues appear to be related to the failed build and AWS authentication issues, and not with the code within the spider itself.

**Comment by ben-nathanson** [comment]
After running it locally and checking the website, this spider is not broken.
