### ISSUE TITLE
icalendar module import error; "Module Not Found Error: No Module Named 'icalendar'"

### ISSUE THREAD

**Issue by maxachis** [pgh-public-meetings/city-scrapers-pitt#131]
This error was reported by several people at our meeting tonight. The problem might have to do with the pipFile not being fully up-to-date. The solution, for the time being, is to run "**pip install icalendar**".

**Comment by dkori** [comment]
This is also causing pull requests to fail because several tests for existing scrapers import icalendar. This may be an issue with the city scrapers core?

**Comment by nicholasmireles** [comment]
Taking a crack at this as an easy first contribution

**Comment by bonfirefan** [comment]
Pat said: "That’s related to having updated pipenv without updating pipenv.lock, if you update the lock file it’ll pick up esprima"

**Comment by bonfirefan** [comment]
This is related to the latest update of legistar. Since legistar is installed via git, I updated with `pipenv install git+https://github.com/opencivicdata/python-legistar-scraper.git@master#egg=legistar`

This update should force pipenv to find legistar's new dependencies, including icalendar and esprima.

**Comment by ben-nathanson** [comment]
Closed by #142
