### ISSUE TITLE
[Sentry] [pa_liquorboard] local variable referenced before assignment

### ISSUE THREAD

**Issue by bonfirefan** [pgh-public-meetings/city-scrapers-pitt#178]
Error: `[pa_liquorboard] UnboundLocalError("local variable 'found_start_hour' referenced before assignment")`
Check if website / website format is constant

**Comment by TylerDunlap** [comment]
Hello,
I'm a new contributor.
looking at the website and an archived copy it looks like the start time was removed:

current:
![current](https://user-images.githubusercontent.com/8662485/94448270-b471eb00-0178-11eb-8f4f-9a4630c8b073.jpg)

previous:
![previous](https://user-images.githubusercontent.com/8662485/94448403-d9665e00-0178-11eb-9def-6339fcb94f91.jpg)

**Comment by ben-nathanson** [comment]
This is the kind of change we wanted to catch when we refactored pa_liquorboard a few months ago. Although if I were doing it again I would have thrown a more explicit exception. 

What's even more interesting is that the changes to the website make it such that the start time does not appear anywhere except for the minutes. I think our only option from here would be to assume a start time of 11:00 AM (which I'm not crazy about since it potentially brings down the accuracy/flexibility of the calendar) and call this out in the `time_notes` field.

**Comment by ben-nathanson** [comment]
Also, @TylerDunlap, we're glad to have you! Feel free to ping me if you have any questions as far as getting started.
